---
name: Authen-Simple-DBM
version: 0.1
author:
  - 'Christian Hansen C<ch@ngmedia.com>'
abstract: Simple DBM authentication
license: perl
requires:
  Authen::Simple: 0.3
provides:
  Authen::Simple::DBM:
    file: lib/Authen/Simple/DBM.pm
    version: 0.1
generated_by: Module::Build version 0.2611
